# --- BACKEND VENTAS ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend-ventas
  labels:
    app: innovatech-backend-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-backend-ventas
  template:
    metadata:
      labels:
        app: innovatech-backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: 003486653797.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/innovatech_db?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password123"
---
apiVersion: v1
kind: Service
metadata:
  name: innovatech-backend-ventas-service
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: innovatech-backend-ventas
---
# --- BACKEND DESPACHOS ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend-despachos
  labels:
    app: innovatech-backend-despachos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-backend-despachos
  template:
    metadata:
      labels:
        app: innovatech-backend-despachos
    spec:
      containers:
      - name: backend-despachos
        image: 003486653797.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/innovatech_db?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password123"
---
apiVersion: v1
kind: Service
metadata:
  name: innovatech-backend-despachos-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: innovatech-backend-despachos 