name: CI/CD Pipeline Innovatech

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- CONSTRUCCIÓN Y SUBIDA ---

      - name: Construir y subir imagen (Frontend)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-frontend 
        run: |
          cd "proyecto semestral/front_despacho"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Construir y subir imagen (Backend Ventas)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-backend-ventas
        run: |
          cd "proyecto semestral/back-Ventas_SpringBoot"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Construir y subir imagen (Backend Despachos)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-backend-despachos
        run: |
          cd "proyecto semestral/back-Despachos_SpringBoot"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # --- DESPLIEGUE AUTOMÁTICO ---

      - name: Actualizar configuración de kubeconfig
        run: |
          aws eks update-kubeconfig --name innovatech-cluster --region us-east-1

      - name: Desplegar en Kubernetes
        run: |
          kubectl apply -f "proyecto semestral/k8s/"
          kubectl rollout restart deployment/innovatech-frontend
          kubectl rollout restart deployment/innovatech-backend-ventas
          kubectl rollout restart deployment/innovatech-backend-despachos